import type { ProjectFiles } from '@/types';
import type { TemporalContext } from '@/lib/prompts/temporal-context';
import type { BusinessProfileData } from '@/lib/discovery/types';
import { buildBusinessContextBlock } from '@/lib/discovery/build-business-context';
import { getBaseRulesSection } from '@/lib/prompts/sections/base-rules';
import {
  buildCurrentWebsiteBlock,
  buildEditModeBlock,
  buildFirstGenerationBlock,
  buildTemporalBlock,
  LAYOUT_ARCHETYPES_SECTION,
} from '@/lib/prompts/sections/context-blocks';
import { INTERACTIVITY_SECTION } from '@/lib/prompts/sections/interactivity';
import { TOOL_OUTPUT_FORMAT_SECTION } from '@/lib/prompts/sections/tool-output-format';
import { UI_UX_GUIDELINES_SECTION } from '@/lib/prompts/sections/ui-ux-guidelines';

export interface SystemPromptParts {
  stable: string;
  dynamic: string;
}

const IDENTITY_LINE = `You are WebBuilder, an expert web designer and developer who creates distinctive, production-ready websites. You generate complete, self-contained HTML pages that look like they were designed by a professional, not generated by AI.`;

const CLOSING_LINE = `IMPORTANT: Be concise in your explanation. Focus on delivering excellent HTML.`;

const CREATIVE_DIRECTION_SECTION = `<creative_direction>
Fight generic "AI-generated" aesthetics actively. Every design choice should feel intentional and distinctive.

Typography: Pick distinctive, lesser-known Google Fonts. NEVER default to Inter, DM Sans, Roboto, Open Sans, Poppins, Montserrat, Space Grotesk, or system fonts. The Google Fonts catalog has 1700+ options — explore it.
Color: Dominant colors with sharp accents outperform timid, evenly-distributed palettes. Draw from real-world aesthetics (vintage travel posters, Japanese print design, mid-century modern, brutalism) not SaaS templates.
Backgrounds: Create atmosphere — layer CSS gradients, use geometric SVG patterns, add contextual texture. NEVER default to plain white/gray backgrounds.
Layout: Follow your assigned layout archetype. Break grid monotony with the techniques in layout_techniques. A predictable 3-column card grid is the hallmark of AI-generated design.
Motion: Focus on high-impact moments — one orchestrated page load with staggered reveals creates more delight than scattered micro-interactions.

Vary between light and dark themes, different font pairings, different aesthetic moods across generations. The best designs feel inevitable in hindsight but surprising at first glance.
</creative_direction>`;

/**
 * Returns the system prompt split into stable (cacheable) and dynamic parts.
 * The stable part contains the identity, base rules, UI/UX guidelines, and tool format —
 * content that rarely changes between requests. The dynamic part contains temporal context,
 * current website state, and edit mode instructions.
 */
export function getSystemPromptParts(
  currentFiles?: ProjectFiles,
  temporalContext?: TemporalContext,
  userPrompt?: string,
  provider?: string,
  modelId?: string,
  businessProfile?: BusinessProfileData | null,
): SystemPromptParts {
  const isFirstGeneration = !currentFiles || !Object.keys(currentFiles).some(f => f.endsWith('.html'));
  const toolSection = TOOL_OUTPUT_FORMAT_SECTION;

  const stable = `${IDENTITY_LINE}

${getBaseRulesSection(isFirstGeneration)}
${UI_UX_GUIDELINES_SECTION}
${CREATIVE_DIRECTION_SECTION}
${LAYOUT_ARCHETYPES_SECTION}
${toolSection}
${INTERACTIVITY_SECTION}`;

  const dynamic = `${buildTemporalBlock(temporalContext)}${buildBusinessContextBlock(businessProfile ?? null)}${buildFirstGenerationBlock(isFirstGeneration, userPrompt)}${buildCurrentWebsiteBlock(currentFiles)}${buildEditModeBlock(currentFiles)}

${CLOSING_LINE}`;

  return { stable, dynamic };
}

export function getSystemPrompt(
  currentFiles?: ProjectFiles,
  temporalContext?: TemporalContext,
  userPrompt?: string,
  provider?: string,
  modelId?: string,
  businessProfile?: BusinessProfileData | null,
): string {
  const { stable, dynamic } = getSystemPromptParts(currentFiles, temporalContext, userPrompt, provider, modelId, businessProfile);
  return stable + '\n' + dynamic;
}
