import type { ProjectFiles } from '@/types';
import type { TemporalContext } from '@/lib/prompts/temporal-context';
import type { DesignBrief } from '@/lib/design-brief/types';
import { getBaseRulesSection } from '@/lib/prompts/sections/base-rules';
import {
  buildCurrentWebsiteBlock,
  buildDesignBriefBlock,
  buildEditModeBlock,
  buildFirstGenerationBlock,
  buildTemporalBlock,
} from '@/lib/prompts/sections/context-blocks';
import { TOOL_OUTPUT_FORMAT_SECTION } from '@/lib/prompts/sections/tool-output-format';
import { UI_UX_GUIDELINES_SECTION } from '@/lib/prompts/sections/ui-ux-guidelines';

interface DesignBriefContext {
  brief: DesignBrief;
  sharedStyles: string;
  headTags: string;
}

export function getSystemPrompt(
  currentFiles?: ProjectFiles,
  temporalContext?: TemporalContext,
  designBriefContext?: DesignBriefContext,
): string {
  const isFirstGeneration = !currentFiles?.['index.html'];
  const hasDesignBrief = isFirstGeneration && !!designBriefContext;

  return `You are WebBuilder, an expert web designer and developer who creates distinctive, production-ready websites. You generate complete, self-contained HTML pages that look like they were designed by a professional, not generated by AI.

${getBaseRulesSection(isFirstGeneration)}
${isFirstGeneration ? '\n' + UI_UX_GUIDELINES_SECTION + '\n' : ''}
${TOOL_OUTPUT_FORMAT_SECTION}
${buildTemporalBlock(temporalContext)}${hasDesignBrief ? buildDesignBriefBlock(designBriefContext.brief, designBriefContext.sharedStyles, designBriefContext.headTags) : buildFirstGenerationBlock(isFirstGeneration)}${buildCurrentWebsiteBlock(currentFiles)}${buildEditModeBlock(currentFiles)}

IMPORTANT: Be concise in your explanation. Focus on delivering excellent HTML.`;
}
