export interface CuratedPalette {
  name: string;
  colors: string[];
  tags: string[];
  roles: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    surface: string;
    text: string;
    textMuted: string;
  };
  scheme: 'light' | 'dark';
}

export const CURATED_PALETTES: CuratedPalette[] = [
  // ── Light Palettes ──────────────────────────────────────────────

  // Warm / Restaurant / Food
  {
    name: 'Tuscan Kitchen',
    colors: ['c1440e', 'e77d11', 'fcd9b6', 'faf6f1', 'ffffff'],
    tags: ['warm', 'earthy', 'restaurant', 'bold'],
    roles: {
      primary: '#c1440e',
      secondary: '#e77d11',
      accent: '#c1440e',
      background: '#faf6f1',
      surface: '#ffffff',
      text: '#2b1810',
      textMuted: '#7a5c4f',
    },
    scheme: 'light',
  },
  {
    name: 'Spice Market',
    colors: ['d35400', 'e74c3c', 'f39c12', 'fef9ef', 'ffffff'],
    tags: ['warm', 'vibrant', 'restaurant', 'bold'],
    roles: {
      primary: '#d35400',
      secondary: '#e74c3c',
      accent: '#f39c12',
      background: '#fef9ef',
      surface: '#ffffff',
      text: '#2c1a0e',
      textMuted: '#7a6252',
    },
    scheme: 'light',
  },
  {
    name: 'Harvest Table',
    colors: ['8b5e3c', 'c49a6c', 'd4a574', 'f7f2ec', 'ffffff'],
    tags: ['warm', 'earthy', 'muted', 'restaurant', 'nature'],
    roles: {
      primary: '#8b5e3c',
      secondary: '#c49a6c',
      accent: '#d4a574',
      background: '#f7f2ec',
      surface: '#ffffff',
      text: '#2d2015',
      textMuted: '#7a6b5d',
    },
    scheme: 'light',
  },
  {
    name: 'Saffron Bloom',
    colors: ['b7410e', 'ff8c42', 'ffd166', 'fffbf0', 'ffffff'],
    tags: ['warm', 'vibrant', 'playful', 'restaurant', 'ecommerce'],
    roles: {
      primary: '#b7410e',
      secondary: '#ff8c42',
      accent: '#ffd166',
      background: '#fffbf0',
      surface: '#ffffff',
      text: '#2b1a0f',
      textMuted: '#7d6550',
    },
    scheme: 'light',
  },

  // Cool / SaaS / Corporate
  {
    name: 'Arctic Blue',
    colors: ['1a56db', '3b82f6', '93c5fd', 'f0f6ff', 'ffffff'],
    tags: ['cool', 'minimal', 'saas', 'corporate'],
    roles: {
      primary: '#1a56db',
      secondary: '#3b82f6',
      accent: '#1a56db',
      background: '#f0f6ff',
      surface: '#ffffff',
      text: '#111827',
      textMuted: '#6b7280',
    },
    scheme: 'light',
  },
  {
    name: 'Slate Pro',
    colors: ['334155', '475569', '0ea5e9', 'f8fafc', 'ffffff'],
    tags: ['cool', 'minimal', 'corporate', 'saas'],
    roles: {
      primary: '#334155',
      secondary: '#475569',
      accent: '#0ea5e9',
      background: '#f8fafc',
      surface: '#ffffff',
      text: '#0f172a',
      textMuted: '#64748b',
    },
    scheme: 'light',
  },
  {
    name: 'Cerulean Tide',
    colors: ['0369a1', '0284c7', '38bdf8', 'f0f9ff', 'ffffff'],
    tags: ['cool', 'bold', 'saas', 'healthcare'],
    roles: {
      primary: '#0369a1',
      secondary: '#0284c7',
      accent: '#38bdf8',
      background: '#f0f9ff',
      surface: '#ffffff',
      text: '#0c1829',
      textMuted: '#5c7a94',
    },
    scheme: 'light',
  },
  {
    name: 'Trust Navy',
    colors: ['1e3a5f', '2563eb', '60a5fa', 'f5f8ff', 'ffffff'],
    tags: ['cool', 'elegant', 'fintech', 'legal', 'corporate'],
    roles: {
      primary: '#1e3a5f',
      secondary: '#2563eb',
      accent: '#60a5fa',
      background: '#f5f8ff',
      surface: '#ffffff',
      text: '#111827',
      textMuted: '#6b7280',
    },
    scheme: 'light',
  },

  // Elegant / Luxury
  {
    name: 'Champagne Gold',
    colors: ['8b6f47', 'c9a96e', 'e8d5b5', 'faf8f4', 'ffffff'],
    tags: ['elegant', 'warm', 'luxury', 'beauty'],
    roles: {
      primary: '#8b6f47',
      secondary: '#c9a96e',
      accent: '#8b6f47',
      background: '#faf8f4',
      surface: '#ffffff',
      text: '#1f1a14',
      textMuted: '#7d7062',
    },
    scheme: 'light',
  },
  {
    name: 'Ivory Rose',
    colors: ['9f1239', 'e11d48', 'fda4af', 'fff5f7', 'ffffff'],
    tags: ['elegant', 'bold', 'beauty', 'luxury'],
    roles: {
      primary: '#9f1239',
      secondary: '#e11d48',
      accent: '#fda4af',
      background: '#fff5f7',
      surface: '#ffffff',
      text: '#1a1012',
      textMuted: '#7a6068',
    },
    scheme: 'light',
  },
  {
    name: 'Mauve Silk',
    colors: ['6d28d9', '8b5cf6', 'c4b5fd', 'f7f5ff', 'ffffff'],
    tags: ['elegant', 'cool', 'luxury', 'creative'],
    roles: {
      primary: '#6d28d9',
      secondary: '#8b5cf6',
      accent: '#c4b5fd',
      background: '#f7f5ff',
      surface: '#ffffff',
      text: '#1c1033',
      textMuted: '#6e6088',
    },
    scheme: 'light',
  },

  // Healthcare / Wellness
  {
    name: 'Ocean Calm',
    colors: ['0d9488', '14b8a6', '5eead4', 'f0fdfa', 'ffffff'],
    tags: ['cool', 'muted', 'healthcare', 'nature'],
    roles: {
      primary: '#0d9488',
      secondary: '#14b8a6',
      accent: '#5eead4',
      background: '#f0fdfa',
      surface: '#ffffff',
      text: '#0f2b27',
      textMuted: '#5a7d78',
    },
    scheme: 'light',
  },
  {
    name: 'Healing Green',
    colors: ['047857', '059669', '34d399', 'ecfdf5', 'ffffff'],
    tags: ['cool', 'muted', 'healthcare', 'nature'],
    roles: {
      primary: '#047857',
      secondary: '#059669',
      accent: '#34d399',
      background: '#ecfdf5',
      surface: '#ffffff',
      text: '#0b2620',
      textMuted: '#4e7a6e',
    },
    scheme: 'light',
  },
  {
    name: 'Soft Lavender',
    colors: ['7c3aed', '8b5cf6', 'ddd6fe', 'f5f3ff', 'ffffff'],
    tags: ['cool', 'pastel', 'healthcare', 'beauty'],
    roles: {
      primary: '#7c3aed',
      secondary: '#8b5cf6',
      accent: '#ddd6fe',
      background: '#f5f3ff',
      surface: '#ffffff',
      text: '#1e1433',
      textMuted: '#6b5f82',
    },
    scheme: 'light',
  },

  // E-commerce / Playful
  {
    name: 'Coral Pop',
    colors: ['e63946', 'f97316', 'fbbf24', 'fffbeb', 'ffffff'],
    tags: ['warm', 'vibrant', 'playful', 'ecommerce'],
    roles: {
      primary: '#e63946',
      secondary: '#f97316',
      accent: '#fbbf24',
      background: '#fffbeb',
      surface: '#ffffff',
      text: '#1f1411',
      textMuted: '#7a6252',
    },
    scheme: 'light',
  },
  {
    name: 'Mint Fresh',
    colors: ['059669', '10b981', '6ee7b7', 'ecfdf5', 'ffffff'],
    tags: ['cool', 'playful', 'ecommerce', 'nature'],
    roles: {
      primary: '#059669',
      secondary: '#10b981',
      accent: '#6ee7b7',
      background: '#ecfdf5',
      surface: '#ffffff',
      text: '#0b2620',
      textMuted: '#4e7a6e',
    },
    scheme: 'light',
  },
  {
    name: 'Sunset Commerce',
    colors: ['dc2626', 'f59e0b', 'fde68a', 'fffef5', 'ffffff'],
    tags: ['warm', 'bold', 'ecommerce', 'vibrant'],
    roles: {
      primary: '#dc2626',
      secondary: '#f59e0b',
      accent: '#fde68a',
      background: '#fffef5',
      surface: '#ffffff',
      text: '#1a1006',
      textMuted: '#7c6d4f',
    },
    scheme: 'light',
  },

  // Creative / Portfolio
  {
    name: 'Electric Indigo',
    colors: ['4f46e5', '6366f1', 'a5b4fc', 'eef2ff', 'ffffff'],
    tags: ['cool', 'bold', 'creative', 'portfolio'],
    roles: {
      primary: '#4f46e5',
      secondary: '#6366f1',
      accent: '#a5b4fc',
      background: '#eef2ff',
      surface: '#ffffff',
      text: '#1e1b4b',
      textMuted: '#6366f1',
    },
    scheme: 'light',
  },
  {
    name: 'Flamingo Studio',
    colors: ['db2777', 'ec4899', 'f9a8d4', 'fdf2f8', 'ffffff'],
    tags: ['warm', 'vibrant', 'creative', 'beauty', 'playful'],
    roles: {
      primary: '#db2777',
      secondary: '#ec4899',
      accent: '#f9a8d4',
      background: '#fdf2f8',
      surface: '#ffffff',
      text: '#2e0f1f',
      textMuted: '#8a5672',
    },
    scheme: 'light',
  },
  {
    name: 'Neon Tangerine',
    colors: ['ea580c', 'f97316', 'fdba74', 'fff7ed', 'ffffff'],
    tags: ['warm', 'bold', 'creative', 'portfolio'],
    roles: {
      primary: '#ea580c',
      secondary: '#f97316',
      accent: '#fdba74',
      background: '#fff7ed',
      surface: '#ffffff',
      text: '#2b1508',
      textMuted: '#7c5e3d',
    },
    scheme: 'light',
  },

  // Education
  {
    name: 'Scholar Blue',
    colors: ['1d4ed8', '3b82f6', '93c5fd', 'eff6ff', 'ffffff'],
    tags: ['cool', 'minimal', 'education', 'corporate'],
    roles: {
      primary: '#1d4ed8',
      secondary: '#3b82f6',
      accent: '#93c5fd',
      background: '#eff6ff',
      surface: '#ffffff',
      text: '#0f1a35',
      textMuted: '#5b6f8f',
    },
    scheme: 'light',
  },
  {
    name: 'Campus Green',
    colors: ['15803d', '22c55e', '86efac', 'f0fdf4', 'ffffff'],
    tags: ['cool', 'playful', 'education', 'nature'],
    roles: {
      primary: '#15803d',
      secondary: '#22c55e',
      accent: '#86efac',
      background: '#f0fdf4',
      surface: '#ffffff',
      text: '#0a2b16',
      textMuted: '#4d7a5e',
    },
    scheme: 'light',
  },

  // Earthy / Nature
  {
    name: 'Forest Floor',
    colors: ['3d5a3e', '6b8f71', 'a8c5a0', 'f4f8f3', 'ffffff'],
    tags: ['earthy', 'muted', 'nature', 'healthcare'],
    roles: {
      primary: '#3d5a3e',
      secondary: '#6b8f71',
      accent: '#a8c5a0',
      background: '#f4f8f3',
      surface: '#ffffff',
      text: '#1a2b1a',
      textMuted: '#5e7a60',
    },
    scheme: 'light',
  },
  {
    name: 'Desert Sand',
    colors: ['92400e', 'b45309', 'd4a574', 'fdf8f0', 'ffffff'],
    tags: ['warm', 'earthy', 'nature', 'restaurant'],
    roles: {
      primary: '#92400e',
      secondary: '#b45309',
      accent: '#d4a574',
      background: '#fdf8f0',
      surface: '#ffffff',
      text: '#2b1d0e',
      textMuted: '#7a6548',
    },
    scheme: 'light',
  },
  {
    name: 'Sage & Stone',
    colors: ['57716e', '7d9b97', 'b5cec9', 'f2f7f6', 'ffffff'],
    tags: ['earthy', 'muted', 'minimal', 'nature', 'healthcare'],
    roles: {
      primary: '#57716e',
      secondary: '#7d9b97',
      accent: '#b5cec9',
      background: '#f2f7f6',
      surface: '#ffffff',
      text: '#1a2625',
      textMuted: '#5e7674',
    },
    scheme: 'light',
  },

  // Pastel
  {
    name: 'Blush Petal',
    colors: ['be185d', 'f472b6', 'fbcfe8', 'fef1f7', 'ffffff'],
    tags: ['pastel', 'warm', 'beauty', 'playful'],
    roles: {
      primary: '#be185d',
      secondary: '#f472b6',
      accent: '#fbcfe8',
      background: '#fef1f7',
      surface: '#ffffff',
      text: '#2e0f1f',
      textMuted: '#8a5672',
    },
    scheme: 'light',
  },
  {
    name: 'Sky Drift',
    colors: ['0284c7', '38bdf8', 'bae6fd', 'f0f9ff', 'ffffff'],
    tags: ['pastel', 'cool', 'saas', 'education'],
    roles: {
      primary: '#0284c7',
      secondary: '#38bdf8',
      accent: '#bae6fd',
      background: '#f0f9ff',
      surface: '#ffffff',
      text: '#0c1829',
      textMuted: '#5c7a94',
    },
    scheme: 'light',
  },
  {
    name: 'Peach Cream',
    colors: ['c2410c', 'fb923c', 'fed7aa', 'fff7ed', 'ffffff'],
    tags: ['pastel', 'warm', 'beauty', 'restaurant'],
    roles: {
      primary: '#c2410c',
      secondary: '#fb923c',
      accent: '#fed7aa',
      background: '#fff7ed',
      surface: '#ffffff',
      text: '#2b1508',
      textMuted: '#7c5e3d',
    },
    scheme: 'light',
  },

  // Fintech / Legal
  {
    name: 'Obsidian Trust',
    colors: ['1e293b', '334155', '0ea5e9', 'f8fafc', 'ffffff'],
    tags: ['cool', 'elegant', 'fintech', 'legal'],
    roles: {
      primary: '#1e293b',
      secondary: '#334155',
      accent: '#0ea5e9',
      background: '#f8fafc',
      surface: '#ffffff',
      text: '#0f172a',
      textMuted: '#64748b',
    },
    scheme: 'light',
  },
  {
    name: 'Emerald Vault',
    colors: ['064e3b', '047857', '10b981', 'ecfdf5', 'ffffff'],
    tags: ['cool', 'elegant', 'fintech', 'corporate'],
    roles: {
      primary: '#064e3b',
      secondary: '#047857',
      accent: '#10b981',
      background: '#ecfdf5',
      surface: '#ffffff',
      text: '#0b2620',
      textMuted: '#4e7a6e',
    },
    scheme: 'light',
  },

  // ── Dark Palettes ──────────────────────────────────────────────

  {
    name: 'Midnight Navy',
    colors: ['0f172a', '1e293b', '3b82f6', '60a5fa', '93c5fd'],
    tags: ['dark', 'cool', 'saas', 'corporate'],
    roles: {
      primary: '#3b82f6',
      secondary: '#60a5fa',
      accent: '#93c5fd',
      background: '#0f172a',
      surface: '#1e293b',
      text: '#f1f5f9',
      textMuted: '#94a3b8',
    },
    scheme: 'dark',
  },
  {
    name: 'Charcoal Ember',
    colors: ['18181b', '27272a', 'ef4444', 'f97316', 'fbbf24'],
    tags: ['dark', 'warm', 'bold', 'creative', 'restaurant'],
    roles: {
      primary: '#ef4444',
      secondary: '#f97316',
      accent: '#fbbf24',
      background: '#18181b',
      surface: '#27272a',
      text: '#f4f4f5',
      textMuted: '#a1a1aa',
    },
    scheme: 'dark',
  },
  {
    name: 'Deep Space',
    colors: ['0a0a1a', '151530', '6366f1', '818cf8', 'a5b4fc'],
    tags: ['dark', 'cool', 'saas', 'creative'],
    roles: {
      primary: '#6366f1',
      secondary: '#818cf8',
      accent: '#a5b4fc',
      background: '#0a0a1a',
      surface: '#151530',
      text: '#e8e8f0',
      textMuted: '#9494b8',
    },
    scheme: 'dark',
  },
  {
    name: 'Noir Gold',
    colors: ['0a0a0a', '1a1a1a', 'c9a96e', 'e8d5b5', 'f5ecd7'],
    tags: ['dark', 'luxury', 'elegant', 'restaurant'],
    roles: {
      primary: '#c9a96e',
      secondary: '#e8d5b5',
      accent: '#f5ecd7',
      background: '#0a0a0a',
      surface: '#1a1a1a',
      text: '#f0ebe0',
      textMuted: '#9a9080',
    },
    scheme: 'dark',
  },
  {
    name: 'Cyber Teal',
    colors: ['0a1a1a', '0f2a2a', '14b8a6', '2dd4bf', '5eead4'],
    tags: ['dark', 'cool', 'saas', 'fintech'],
    roles: {
      primary: '#14b8a6',
      secondary: '#2dd4bf',
      accent: '#5eead4',
      background: '#0a1a1a',
      surface: '#0f2a2a',
      text: '#e0f5f0',
      textMuted: '#80b8ad',
    },
    scheme: 'dark',
  },
  {
    name: 'Obsidian Rose',
    colors: ['1a0a10', '2a1520', 'e11d48', 'fb7185', 'fda4af'],
    tags: ['dark', 'elegant', 'beauty', 'luxury'],
    roles: {
      primary: '#e11d48',
      secondary: '#fb7185',
      accent: '#fda4af',
      background: '#1a0a10',
      surface: '#2a1520',
      text: '#f5e0e8',
      textMuted: '#b08090',
    },
    scheme: 'dark',
  },
  {
    name: 'Dark Forest',
    colors: ['0a1a0f', '152a1a', '059669', '34d399', '6ee7b7'],
    tags: ['dark', 'earthy', 'nature', 'fintech'],
    roles: {
      primary: '#059669',
      secondary: '#34d399',
      accent: '#6ee7b7',
      background: '#0a1a0f',
      surface: '#152a1a',
      text: '#e0f5ec',
      textMuted: '#80b89a',
    },
    scheme: 'dark',
  },
  {
    name: 'Onyx Purple',
    colors: ['10051a', '1a0f2e', '8b5cf6', 'a78bfa', 'c4b5fd'],
    tags: ['dark', 'cool', 'creative', 'portfolio'],
    roles: {
      primary: '#8b5cf6',
      secondary: '#a78bfa',
      accent: '#c4b5fd',
      background: '#10051a',
      surface: '#1a0f2e',
      text: '#ede8f5',
      textMuted: '#9888b5',
    },
    scheme: 'dark',
  },
];
