/**
 * Fetches the full Google Fonts catalog and writes a generated TypeScript module
 * exporting a Set of all valid font family names (lowercased for lookup).
 *
 * Usage:  npx tsx scripts/fetch-google-fonts.ts
 *
 * Uses the public Google Fonts metadata endpoint (no API key required).
 * The generated file is committed to git so it's always available at runtime.
 * Re-run periodically to pick up newly added fonts.
 */

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, '../src/lib/google-fonts-catalog.ts');

const METADATA_URL = 'https://fonts.google.com/metadata/fonts';

interface FontMetadata {
  familyMetadataList: Array<{ family: string }>;
}

async function main() {
  console.log('Fetching Google Fonts catalog...');
  const res = await fetch(METADATA_URL);
  if (!res.ok) {
    throw new Error(`Google Fonts metadata returned ${res.status}: ${await res.text()}`);
  }

  const data = (await res.json()) as FontMetadata;
  const families = data.familyMetadataList.map((item) => item.family).sort();

  console.log(`Fetched ${families.length} font families.`);

  const timestamp = new Date().toISOString();
  const lines = [
    `// Auto-generated by scripts/fetch-google-fonts.ts — do not edit manually`,
    `// Last updated: ${timestamp}`,
    `// Total fonts: ${families.length}`,
    ``,
    `const GOOGLE_FONTS_LIST: string[] = ${JSON.stringify(families, null, 2)};`,
    ``,
    `/** Set of all valid Google Font family names (lowercased for case-insensitive lookup) */`,
    `export const GOOGLE_FONTS_SET = new Set(GOOGLE_FONTS_LIST.map(f => f.toLowerCase()));`,
    ``,
    `/** Map from lowercased name to canonical (original-case) Google Font family name */`,
    `export const GOOGLE_FONTS_CANONICAL = new Map(GOOGLE_FONTS_LIST.map(f => [f.toLowerCase(), f]));`,
    ``,
  ];

  writeFileSync(OUTPUT_PATH, lines.join('\n'), 'utf-8');
  console.log(`Written to ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error('Failed to fetch Google Fonts:', err);
  process.exit(1);
});
